name: Build

on:
  push:
  pull_request:

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - name: Set up Python
        uses: actions/setup-python@v7
        with:
          python-version: "3.x"
      - name: Install Poetry
        run: pipx install poetry
      - name: Poetry check
        run: poetry check
      - name: Build
        run: poetry build
      - name: Install twine
        run: pipx install twine
      - name: Twine check
        run: twine check dist/*
